branch-defaults:
  main:
    environment: Hellonode-env-1
global:
  application_name: hello-node
  default_platform: Node.js 14 running on 64bit Amazon Linux 2/5.4.5
  default_region: ap-northeast-1
  sc: git